#!/usr/bin/env python3
import mrdata

def main():
    data_set = []
    data = load_file("sub1.csv")
    for i in data:
        values = i.split(',')
        data_row = mrdata.DataRow(values[0], values[1], values[2], values[3], values[4], values[5])
        data_set.append(data_row)

    false_responses = []
    
    print("KORREKTA SVAR:")
    for data_row in data_set:
        error_type = data_row.get_error_type()
        if error_type == mrdata.TP or error_type == mrdata.TN:
            print("Trial: " + data_row.trial + ", Image: " + data_row.image_file + ", Time: " + data_row.time)
        else:
            false_responses.append(data_row)
    print("FALSKA SVAR:")
    for data_row in false_responses:
        print("Trial: " + data_row.trial + ", Image: " + data_row.image_file + ", Time: " + data_row.time)


def load_file(name):
    with open("/home/aleja767/csv/" + name, 'r') as reader:
        return reader.read().splitlines()

if __name__ == "__main__":
    main()
